### ISSUE TITLE
Problem with latest version

### ISSUE THREAD

**Issue by dano184** [carfup/XTBPlugins.DeltaStepsBetweenEnvironments#13]
Hi,
I just accepted the latest version (1.2018.12.10), but now when I try to load assemblies (as an Admin user), I get a message that I don't have Solution Read privileges.  I've re-installed one of the older versions(1.218.5.9) , which works ok.

**Comment by carfup** [comment]
Hi Dano,
First of all, thanks for using the plugin !

Can you make sure you have read permission on Solution entity in the Customization tab for the "Source instance" defined in the plugin ? Just tried on my side, with the admin user (sys admin and sys customizer roles and it's all fine), as well as with a user which is "functional" and i have the message as expected.

The aim of that message, was to let know the user of the lacking of permissions before getting an exception from the CRM when processing

Let me know !

**Comment by dano184** [comment]
Thanks for the quick response.

I’ve confirmed my user have Admin privileges.  Prior to the upgrade, the same user on the same systems worked fine.

Is there some config in the tool that I have missed?


[cid:image003.png@01D492C9.920CA110]
[cid:image002.png@01D492C9.BC4C8440]


[cid:image001.png@01D492C8.D5F64CB0]

**Comment by carfup** [comment]
Hi Dano184,
A new version was released recently, can you tell me if your issue is still ocurring ?

**Comment by carfup** [comment]
Since we have no news, i close the issue but feel free to reopen it if necessary.
