### ISSUE TITLE
Delta Plugin steps between environments doesn't work

### ISSUE THREAD

**Issue by daryllabar** [carfup/XTBPlugins.DeltaStepsBetweenEnvironments#14]
Clicking load Solution actually loads the assemblies, but then when I click compare, it says they are not solutions.  Selecting Assembly and then Load Assemblies gives an error "Make sure your user has the prvReeadSolution privilege to load the solution." when loading the solutions.  I'm a system admin in the environment, so I should have all CRM privs.

**Comment by carfup** [comment]
Hi Daryl,

Thanks for the report and the commit ! 
I saw that error last week, just didn't get time to fix it right away.
And seeing my code (which is years old now), i really need to improve it now !

**Comment by carfup** [comment]
#21 Changes included in the latest version.
Huge thanks for your contribution Daryl !
